### ISSUE TITLE
Odd pictures, #2f2d13 and copyright

### ISSUE THREAD

**Issue by cieraclaire** [acgd-webdev-1/navigation-highlight#1]
I am not sure why the pictures in markbot look extremely disgruntled and not visible. I have no idea where #2f2d13 is used for. Is it used for the ©Berries.? I also don't know how to make the copyright sign smaller. I tried <small>©</small> in HTML. It must be for css? Can't figure it out. Thanks in advance!
@thomasjbradley

**Comment by thomasjbradley** [comment]
I'm working on the screenshot testing system... I've got a couple improvement ideas.

The `#2f2d13` is the colour of the body text—it isn't black in the screenshots just dark grey.

For the copyright symbol did you set the font-size on the footer?

**Comment by cieraclaire** [comment]
Ah ok! The color makes sense now!

So for the photos, it's showing all of the pictures with an X on the left and it says for example BLUEBERRIES.HTML - 400PX. Do I change it to that size?

I changed the size again in the footer and it's still showing that I need © :s..


________________________________

**Comment by thomasjbradley** [comment]
Screenshots: it's taking a screenshot of your website at 400 px and comparing it to the images in the `screenshot` folder. Then it should be showing you that yours are different with bright pink marks. 

Can you sync your code to GitHub so I can look at the copyright symbol?

**Comment by cieraclaire** [comment]
Ohh, alright, I understand.

I've synced it. I hope you can see it!


________________________________

**Comment by thomasjbradley** [comment]
*Copyright symbol:* Don’t use the entity, `&copy;`, put the actual copyright symbol in, like this `©`.
